export {
    createPool,
    getPool,
    query,
    transaction,
    closePool,
    healthCheck,
    type DatabaseConfig,
    type UserWallet,
    type UserProfile,
    type InviteCode,
    type InviteRecord,
    type AINPCConfig,
    type AITriggerZone,
    type NFTBadge,
    type UserBadge,
    type AIConversation,
    type PointsTransaction,
} from "./PostgreSQLClient";
